language: objective-c  #1
osx_image: xcode7.2 #2
xcode_workspace: PT_ReleaseNotes/PT_ReleaseNotes.xcworkspace #3
xcode_scheme: PT_ReleaseNotes #4
xcode_sdk: macosx10.11 #5
podfile: PT_ReleaseNotes/Podfile

notifications:
email:
recipients:
- sdevore@sdevore.com
on_success: change # default: change
on_failure: always # default: always