platform :osx, "10.9"

abstract_target 'PivotalTracker' do
    pod 'AFNetworking'
    pod 'CocoaLumberjack'
    pod "XCDLumberjackNSLogger", "~> 1.0.2"
    pod "AFNetworkActivityLogger"
    pod 'NSColor-Pantone'
    pod 'NSColor-Crayola'
    pod 'DMTime', :git => 'https://github.com/sdevore/DMTime.git'

    target :PT_ReleaseNotes do
        pod 'SSKeychain'
        pod 'DevMateKit'
    end

    target :PivotTrackerXPC do
                
    end

    target :PT_ReleaseNotesTests do
        pod 'OHHTTPStubs'
        pod 'OCHamcrest', '~> 5.0'
    end
end